/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import components.BordaArredondada;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import model.Cliente;
import controller.ClienteController;
import controller.LocacaoController;
import controller.VeiculoController;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Locacao;
import model.Veiculo;

/**
 *
 * @author aluno.saolucas
 */
public class FrCadLocacao extends javax.swing.JDialog {

    private String id;
    private String nome;

    //Métodos para ler os atributos por fora da classe
    public String getId() {
        return id;
    }

    public String getNome() {
        return nome;
    }

    /**
     * Creates new form FrCadLocacao
     */
    public FrCadLocacao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ajustarColunas();
        this.setLocationRelativeTo(null);
        edtClienteId.setBorder(new BordaArredondada(15));
        edtNomeCliente.setBorder(new BordaArredondada(15));
        edtDataFim.setBorder(new BordaArredondada(15));
        edtDataInicio.setBorder(new BordaArredondada(15));
        edtDataFim.setBorder(new BordaArredondada(15));
        btnCancelar.setBorder(new BordaArredondada(15));
        btnPesquisarCliente.setBorder(new BordaArredondada(15));
        btnSalvar.setBorder(new BordaArredondada(15));
        btnSelecionarVeic.setBorder(new BordaArredondada(15));

        javax.swing.border.Border padding = new javax.swing.border.EmptyBorder(5, 5, 5, 5);
        javax.swing.border.Border line = new javax.swing.border.LineBorder(new java.awt.Color(150, 150, 200), 2, true);
        javax.swing.border.Border roundedBorder = javax.swing.BorderFactory.createCompoundBorder(line, padding);
        jScrollPane1.setBorder(roundedBorder);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        edtClienteId = new javax.swing.JTextField();
        edtNomeCliente = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        edtDataInicio = new javax.swing.JFormattedTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnPesquisarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVeiculo = new javax.swing.JTable();
        btnSelecionarVeic = new javax.swing.JButton();
        edtDataFim = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitulo.setText("Cadastro de Locação");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNome.setText("ID");
        jPanel1.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        edtClienteId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(edtClienteId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 50, 30));

        edtNomeCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(edtNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 260, 30));

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmail.setText("Nome do Cliente:");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        lblSenha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSenha.setText("Data de Inicio");
        jPanel1.add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        edtDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        edtDataInicio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(edtDataInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 220, 30));

        btnSalvar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 150, 30));

        btnCancelar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 150, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Data de Fim");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, 20));

        btnPesquisarCliente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnPesquisarCliente.setText("Pesquisar");
        btnPesquisarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarClienteMouseClicked(evt);
            }
        });
        jPanel1.add(btnPesquisarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 150, 30));

        tblVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Marca", "Ano", "Modelo"
            }
        ));
        jScrollPane1.setViewportView(tblVeiculo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 490, 180));

        btnSelecionarVeic.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSelecionarVeic.setText("Selecionar Veíc.");
        btnSelecionarVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarVeicActionPerformed(evt);
            }
        });
        jPanel1.add(btnSelecionarVeic, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, 170, 30));

        edtDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        edtDataFim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(edtDataFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 220, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarClienteMouseClicked
        FrSelecionarCli telaConsultar = new FrSelecionarCli(null, rootPaneCheckingEnabled);
        telaConsultar.setVisible(true);

        //Quando fechar a tela de consultar vai voltar aqui e testar se selecionou ou não
        if (!telaConsultar.getId().equals("")) {
            edtClienteId.setText(telaConsultar.getId());
            edtNomeCliente.setText(telaConsultar.getNome());
        } else {
            JOptionPane.showMessageDialog(this, "Não foi selecionado um cliente");
        }
    }//GEN-LAST:event_btnPesquisarClienteMouseClicked

    public void pesquisar() {
        //Pega o modelo da grade com suas colunas
        // o 
        DefaultTableModel modeloTabela = (DefaultTableModel) tblVeiculo.getModel();

        //Limpa a grade setando o número de linhas para zero
        modeloTabela.setNumRows(0);

        //Cria um UsuarioController para poder acessar os dados de tbusuario
        VeiculoController controller = new VeiculoController();

        //consulta os usuários e guarda a lista de usuários que encontrou
        List<Veiculo> listaVeiculo = controller.listar();

        //Preencher a grade
        //percorre todos os usuários presentes na lista
        for (Veiculo v : listaVeiculo) {
            //cria um array onde cada posição é o valor das colunas da grade
            Object[] linha = {
                v.getPkVeiculo(), //coluna 0
                v.getMarca(), //coluna 1
                v.getAno(), //coluna 2
                v.getModelo(),
                v.getPlaca()
            };

            //Adiciona o array com os dados do usuário na grade
            modeloTabela.addRow(linha);
        }
    }

    private void btnSelecionarVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarVeicActionPerformed
        FrSelecionarVeic telaSelecionar = new FrSelecionarVeic(null, rootPaneCheckingEnabled);
        telaSelecionar.setVisible(true);
        if (!telaSelecionar.getId().equals("")) {
            DefaultTableModel modelo = (DefaultTableModel) tblVeiculo.getModel();

            modelo.addRow(new Object[]{
                telaSelecionar.getId(),
                telaSelecionar.getAno(),
                telaSelecionar.getModelo(),
                telaSelecionar.getMarca(),
                telaSelecionar.getPlaca(),});

        } else {
            JOptionPane.showMessageDialog(this, "Nenhum Veículo foi selecionado");

        }
    }//GEN-LAST:event_btnSelecionarVeicActionPerformed

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        gravar();
    }//GEN-LAST:event_btnSalvarMouseClicked

    public void gravar() {
        try {
            Locacao l = new Locacao();

            // Data de início e fim
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Date dataInicio = sdf.parse(edtDataInicio.getText());
            Date dataFim = sdf.parse(edtDataFim.getText());

            // Cliente
            int clienteId = Integer.parseInt(edtClienteId.getText());

            // Veículo (assumindo que só um é selecionado por vez)
            int linhaSelecionada = tblVeiculo.getRowCount() - 1;
            if (linhaSelecionada >= 0) {
                int veiculoId = Integer.parseInt(tblVeiculo.getValueAt(linhaSelecionada, 0).toString());

                // Setando os dados
                l.setClienteId(clienteId);
                l.setVeiculoId(veiculoId);
                l.setDataInicio(dataInicio);
                l.setDataFim(dataFim);

                // Salvando
                LocacaoController controller = new LocacaoController();

                if (controller.inserir(l)) {
                    JOptionPane.showMessageDialog(this, "Locação gravada com sucesso");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao gravar locação");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Nenhum veículo selecionado");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao gravar: " + e.getMessage());
        }
    }

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCadLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCadLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCadLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCadLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrCadLocacao dialog = new FrCadLocacao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void ajustarColunas() {
        TableColumn colunaId = tblVeiculo.getColumnModel().getColumn(0);
        colunaId.setMinWidth(40);
        colunaId.setMaxWidth(40);
        colunaId.setPreferredWidth(40);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPesquisarCliente;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSelecionarVeic;
    private javax.swing.JTextField edtClienteId;
    private javax.swing.JFormattedTextField edtDataFim;
    private javax.swing.JFormattedTextField edtDataInicio;
    private javax.swing.JTextField edtNomeCliente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblVeiculo;
    // End of variables declaration//GEN-END:variables
}
