/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author iband
 */
public class FrMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrMenu
     */
    public FrMenu() {
        initComponents();

        //Abre a tela centralizada
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblImagem = new javax.swing.JLabel();
        barMenu = new javax.swing.JMenuBar();
        meCadastro = new javax.swing.JMenu();
        miCadUsuario = new javax.swing.JMenuItem();
        miCadLocacao = new javax.swing.JMenuItem();
        miCadVeiculo = new javax.swing.JMenuItem();
        miCadCliente = new javax.swing.JMenuItem();
        miCadSeguro = new javax.swing.JMenuItem();
        miSair = new javax.swing.JMenuItem();
        meConsulta = new javax.swing.JMenu();
        miConUsuario = new javax.swing.JMenuItem();
        miConVeiculo = new javax.swing.JMenuItem();
        miConSeguro = new javax.swing.JMenuItem();
        miConCliente = new javax.swing.JMenuItem();
        meSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo_locadora.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        barMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        meCadastro.setText("Cadastro");
        meCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        miCadUsuario.setText("Usuário");
        miCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadUsuarioActionPerformed(evt);
            }
        });
        meCadastro.add(miCadUsuario);

        miCadLocacao.setText("Locação");
        miCadLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadLocacaoActionPerformed(evt);
            }
        });
        meCadastro.add(miCadLocacao);

        miCadVeiculo.setText("Veiculo");
        miCadVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadVeiculoActionPerformed(evt);
            }
        });
        meCadastro.add(miCadVeiculo);

        miCadCliente.setText("Cliente");
        miCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadClienteActionPerformed(evt);
            }
        });
        meCadastro.add(miCadCliente);

        miCadSeguro.setText("Seguro");
        miCadSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadSeguroActionPerformed(evt);
            }
        });
        meCadastro.add(miCadSeguro);

        miSair.setText("Sair");
        miSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSairActionPerformed(evt);
            }
        });
        meCadastro.add(miSair);

        barMenu.add(meCadastro);

        meConsulta.setText("Consulta");
        meConsulta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        meConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meConsultaActionPerformed(evt);
            }
        });

        miConUsuario.setText("Usuário");
        miConUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConUsuarioActionPerformed(evt);
            }
        });
        meConsulta.add(miConUsuario);

        miConVeiculo.setText("Veiculo");
        miConVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConVeiculoActionPerformed(evt);
            }
        });
        meConsulta.add(miConVeiculo);

        miConSeguro.setText("Seguro");
        miConSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConSeguroActionPerformed(evt);
            }
        });
        meConsulta.add(miConSeguro);

        miConCliente.setText("Cliente");
        miConCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConClienteActionPerformed(evt);
            }
        });
        meConsulta.add(miConCliente);

        barMenu.add(meConsulta);

        meSobre.setText("Sobre");
        meSobre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        meSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meSobreMouseClicked(evt);
            }
        });
        barMenu.add(meSobre);

        setJMenuBar(barMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void miConUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConUsuarioActionPerformed
      //crio uma tela de cadastro de usuário
      FrConUsuario telaConsulta = new FrConUsuario(this, rootPaneCheckingEnabled);

      //Torno a tela visível
      telaConsulta.setVisible(true);
  }//GEN-LAST:event_miConUsuarioActionPerformed

  private void miConClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConClienteActionPerformed

    FrConClientes telaCliente = new FrConClientes(this, true);
    telaCliente.setVisible(true);

  }//GEN-LAST:event_miConClienteActionPerformed

  private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      URL caminhoImagem = getClass().getResource("/images/user_alterar.png");

      ImageIcon icon = new ImageIcon(caminhoImagem);

      // Define o ícone da janela
      this.setIconImage(icon.getImage());
  }//GEN-LAST:event_formWindowOpened

  private void miSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSairActionPerformed
      this.dispose();
  }//GEN-LAST:event_miSairActionPerformed

  private void miCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadUsuarioActionPerformed
      //crio uma tela de cadastro de usuário
      FrCadUsuario telaCadastro = new FrCadUsuario(this, rootPaneCheckingEnabled);

      //Torno a tela visível
      telaCadastro.setVisible(true);
  }//GEN-LAST:event_miCadUsuarioActionPerformed

  private void meSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meSobreMouseClicked
      FrSobre telaSobre = new FrSobre(this, rootPaneCheckingEnabled);

      telaSobre.setVisible(true);
  }//GEN-LAST:event_meSobreMouseClicked

    private void miCadVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadVeiculoActionPerformed
        FrCadVeiculos telaVeiculo = new FrCadVeiculos(this, rootPaneCheckingEnabled);

        telaVeiculo.setVisible(true);
    }//GEN-LAST:event_miCadVeiculoActionPerformed

    private void miConVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConVeiculoActionPerformed
        FrConVeiculo telaVeiculo = new FrConVeiculo(this, rootPaneCheckingEnabled);

        telaVeiculo.setVisible(true);
    }//GEN-LAST:event_miConVeiculoActionPerformed

    private void miCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadClienteActionPerformed

        FrCadCliente telaCadCliente = new FrCadCliente(null, rootPaneCheckingEnabled);
        
        telaCadCliente.setVisible(true);

    }//GEN-LAST:event_miCadClienteActionPerformed

    private void miCadLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadLocacaoActionPerformed
        FrCadLocacao telaLocacao = new FrCadLocacao(this, rootPaneCheckingEnabled);

        //Torno a tela visível
        telaLocacao.setVisible(true);
    }//GEN-LAST:event_miCadLocacaoActionPerformed

    private void miCadSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadSeguroActionPerformed
        FrCadSeguro telaSeguro = new FrCadSeguro(this, rootPaneCheckingEnabled);

        telaSeguro.setVisible(true);
    }//GEN-LAST:event_miCadSeguroActionPerformed

    private void meConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meConsultaActionPerformed

    }//GEN-LAST:event_meConsultaActionPerformed

    private void miConSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConSeguroActionPerformed
        FrConSeguro telaSeguro = new FrConSeguro(this, rootPaneCheckingEnabled);

        telaSeguro.setVisible(true);
    }//GEN-LAST:event_miConSeguroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JMenu meCadastro;
    private javax.swing.JMenu meConsulta;
    private javax.swing.JMenu meSobre;
    private javax.swing.JMenuItem miCadCliente;
    private javax.swing.JMenuItem miCadLocacao;
    private javax.swing.JMenuItem miCadSeguro;
    private javax.swing.JMenuItem miCadUsuario;
    private javax.swing.JMenuItem miCadVeiculo;
    private javax.swing.JMenuItem miConCliente;
    private javax.swing.JMenuItem miConSeguro;
    private javax.swing.JMenuItem miConUsuario;
    private javax.swing.JMenuItem miConVeiculo;
    private javax.swing.JMenuItem miSair;
    // End of variables declaration//GEN-END:variables
}
