/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClienteController;
import controller.VeiculoController;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Veiculo;

/**
 *
 * @author higor
 */
public class FrSelecionarVeic extends javax.swing.JDialog {

    public String getMarca() {
        return Marca;
    }

    public void setMarca(String Marca) {
        this.Marca = Marca;
    }

    public String getAno() {
        return Ano;
    }

    public void setAno(String Ano) {
        this.Ano = Ano;
    }

    public String getPlaca() {
        return Placa;
    }

    public void setPlaca(String Placa) {
        this.Placa = Placa;
    }

    private String id;
    private String modelo;
    private String Marca;
    private String Ano;
    private String Placa;

    //Métodos para ler os atributos por fora da classe
    public String getId() {
        return id;
    }

    public String getModelo() {
        return modelo;
    }

    /**
     * Creates new form FrSelecionarVeic
     */
    public FrSelecionarVeic(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblTitulo2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVeiculo = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnSelecionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitulo2.setText("Consulta de Veículo");
        jPanel3.add(lblTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        tblVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Marca", "Modelo", "Ano", "Placa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblVeiculo);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 670, 320));

        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVoltar.setText("Voltar");
        jPanel3.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        btnPesquisar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseClicked(evt);
            }
        });
        jPanel3.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        btnSelecionar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSelecionar.setText("Selecionar");
        btnSelecionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSelecionarMouseClicked(evt);
            }
        });
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });
        jPanel3.add(btnSelecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD:src/view/FrConCliente.java
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
=======
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
>>>>>>> higor:src/view/FrSelecionarVeic.java
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD:src/view/FrConCliente.java
    //Limpa a grade setando o número de linhas para zero
    modeloTabela.setNumRows(0);

    //Cria um UsuarioController para poder acessar os dados de tbusuario
    UsuarioController controller = new UsuarioController();
    
    //consulta os usuários e guarda a lista de usuários que encontrou
    List<Usuario> listaUsuarios = controller.consultar();
    
    //Preencher a grade
    //percorre todos os usuários presentes na lista
    for (Usuario usu : listaUsuarios) {
      //cria um array onde cada posição é o valor das colunas da grade
      Object[] linha = {
        usu.getPkUsuario(), //coluna 0
        usu.getNome(), //coluna 1
        usu.getEmail(), //coluna 2
        Utils.converterDateToString(usu.getDataNascUsu()), //coluna 3
        usu.ativoToString() //coluna 4
      };
      
      //Adiciona o array com os dados do usuário na grade
      modeloTabela.addRow(linha);
    }
  }
    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        //Verificar se tem uma linha da grade selecionada
        if (tblClientes.getSelectedRow() != -1) {
            //Se tiver pegar o código do usuário da grade
            int linhaSelecionada = tblClientes.getSelectedRow();
            String textoCelula = tblClientes.getValueAt(linhaSelecionada, 0).toString();
=======
    private void btnPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseClicked
        pesquisar();
    }//GEN-LAST:event_btnPesquisarMouseClicked
>>>>>>> higor:src/view/FrSelecionarVeic.java

    public void pesquisar() {
        //Pega o modelo da grade com suas colunas
        // o 
        DefaultTableModel modeloTabela = (DefaultTableModel) tblVeiculo.getModel();

        //Limpa a grade setando o número de linhas para zero
        modeloTabela.setNumRows(0);

        //Cria um UsuarioController para poder acessar os dados de tbusuario
        VeiculoController controller = new VeiculoController();

        //consulta os usuários e guarda a lista de usuários que encontrou
        List<Veiculo> listaVeiculo = controller.listar();

        //Preencher a grade
        //percorre todos os usuários presentes na lista
        for (Veiculo v : listaVeiculo) {
            //cria um array onde cada posição é o valor das colunas da grade
            Object[] linha = {
                v.getPkVeiculo(), //coluna 0
                v.getMarca(), //coluna 1
                v.getModelo(), //coluna 2
                v.getAno(),
                v.getPlaca()
            };

            //Adiciona o array com os dados do usuário na grade
            modeloTabela.addRow(linha);
        }
    }
    private void btnSelecionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelecionarMouseClicked
        if (tblVeiculo.getSelectedRow() != -1) {
            //Se tiver pegar o código do usuário da grade
            int linhaSelecionada = tblVeiculo.getSelectedRow();
            String textoCelula = tblVeiculo.getValueAt(linhaSelecionada, 0).toString();

            //converter o texto da célula em inteiro
            id = textoCelula;
            String textoNome = tblVeiculo.getValueAt(linhaSelecionada, 1).toString();
            modelo = textoNome;

            String textoMarca = tblVeiculo.getValueAt(linhaSelecionada, 2).toString();
            Marca = textoMarca;
            String textoAno = tblVeiculo.getValueAt(linhaSelecionada, 3).toString();
            Ano = textoAno;
            String textoPlaca = tblVeiculo.getValueAt(linhaSelecionada, 4).toString();
            Placa = textoPlaca;

            this.dispose();
            //com o pkUsuario eu vou criar uma tela de
            //alteração passando o pkUsuario
            //Essa tela irá carregar os dados desse usuário

        }
    }//GEN-LAST:event_btnSelecionarMouseClicked

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelecionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrSelecionarVeic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrSelecionarVeic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrSelecionarVeic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrSelecionarVeic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrSelecionarVeic dialog = new FrSelecionarVeic(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JTable tblVeiculo;
    // End of variables declaration//GEN-END:variables
}
